#!/bin/bash
# Usage: ./scripts/release.sh <version> [<build_number>]
# Example: ./scripts/release.sh 1.4.0 7
#
# End-to-end Bartidy release pipeline:
#   1. Build (Release, Developer ID signed, hardened runtime)
#   2. Verify codesign
#   3. Create + sign DMG
#   4. Notarize + staple
#   5. EdDSA-sign for Sparkle
#   6. Update appcast.xml
#
# Requires:
#   - Xcode + Developer ID Application certificate in keychain
#   - notarytool keychain profile "bartidy-notary"
#   - Sparkle EdDSA key in keychain (generated by .sparkle/bin/generate_keys)
#   - .sparkle/bin/sign_update available

set -euo pipefail

VERSION="${1:-}"
BUILD_NUMBER="${2:-}"

if [[ -z "$VERSION" ]]; then
    echo "Usage: $0 <version> [<build_number>]"
    echo "Example: $0 1.4.0 7"
    exit 1
fi

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

# Derive build number from version (e.g. 1.4.8 -> 10408) so every
# release gets a unique, monotonically increasing CFBundleVersion
# without needing to persist state across CI runs.
if [[ -z "$BUILD_NUMBER" ]]; then
    IFS='.' read -ra V <<< "$VERSION"
    BUILD_NUMBER=$(( ${V[0]:-0} * 10000 + ${V[1]:-0} * 100 + ${V[2]:-0} ))
fi

TEAM_ID="4Z683Z85XA"
SIGN_IDENTITY="Developer ID Application: Heerak Son (${TEAM_ID})"
NOTARY_PROFILE="bartidy-notary"
APP_NAME="Bartidy"
SCHEME="Bartidy"
BUILD_DIR="$REPO_ROOT/build/release"
APP_PATH="$BUILD_DIR/Build/Products/Release/${APP_NAME}.app"
ENTITLEMENTS="$REPO_ROOT/Bartidy/Bartidy.entitlements"
RELEASE_DIR="$REPO_ROOT/release"
DMG_NAME="${APP_NAME}-${VERSION}.dmg"
DMG_PATH="$RELEASE_DIR/$DMG_NAME"
APPCAST_PATH="$REPO_ROOT/appcast.xml"
SIGN_UPDATE="$REPO_ROOT/.sparkle/bin/sign_update"
DOWNLOAD_URL="https://github.com/raki-1203/bartidy/releases/download/v${VERSION}/${DMG_NAME}"

step() {
    echo ""
    echo "==> $1"
}

step "Release: v${VERSION} (build ${BUILD_NUMBER})"

# 1. Clean build with Developer ID signing
step "Clean build (Release, Developer ID signed)"
rm -rf "$BUILD_DIR"
xcodebuild -project Bartidy.xcodeproj \
    -scheme "$SCHEME" \
    -configuration Release \
    -derivedDataPath "$BUILD_DIR" \
    MARKETING_VERSION="$VERSION" \
    CURRENT_PROJECT_VERSION="$BUILD_NUMBER" \
    CODE_SIGN_STYLE=Manual \
    CODE_SIGN_IDENTITY="$SIGN_IDENTITY" \
    DEVELOPMENT_TEAM="$TEAM_ID" \
    CODE_SIGN_ENTITLEMENTS="$ENTITLEMENTS" \
    OTHER_CODE_SIGN_FLAGS="--timestamp --options=runtime" \
    -quiet \
    clean build

if [[ ! -d "$APP_PATH" ]]; then
    echo "❌ Build product missing: $APP_PATH"
    exit 1
fi

# 2a. Re-sign Sparkle nested helpers (xcodebuild Manual mode does not sign them with our identity)
step "Re-sign Sparkle nested components"
SPARKLE_FW="$APP_PATH/Contents/Frameworks/Sparkle.framework"
SIGN_ARGS=(--force --options runtime --timestamp --sign "$SIGN_IDENTITY")

# Sign inside-out
codesign "${SIGN_ARGS[@]}" "$SPARKLE_FW/Versions/B/XPCServices/Downloader.xpc/Contents/MacOS/Downloader"
codesign "${SIGN_ARGS[@]}" "$SPARKLE_FW/Versions/B/XPCServices/Downloader.xpc"
codesign "${SIGN_ARGS[@]}" "$SPARKLE_FW/Versions/B/XPCServices/Installer.xpc/Contents/MacOS/Installer"
codesign "${SIGN_ARGS[@]}" "$SPARKLE_FW/Versions/B/XPCServices/Installer.xpc"
codesign "${SIGN_ARGS[@]}" "$SPARKLE_FW/Versions/B/Autoupdate"
codesign "${SIGN_ARGS[@]}" "$SPARKLE_FW/Versions/B/Updater.app/Contents/MacOS/Updater"
codesign "${SIGN_ARGS[@]}" "$SPARKLE_FW/Versions/B/Updater.app"
codesign "${SIGN_ARGS[@]}" "$SPARKLE_FW"

# Re-sign the outer app so it references the updated Sparkle signatures
codesign "${SIGN_ARGS[@]}" --entitlements "$ENTITLEMENTS" "$APP_PATH"

# 2b. Verify codesign on app
step "Verify app codesign"
codesign --verify --deep --strict --verbose=2 "$APP_PATH"
codesign -dvv "$APP_PATH" 2>&1 | grep -E "Authority|TeamIdentifier|Identifier|Runtime" || true

# 3. Create + sign DMG
step "Create DMG"
mkdir -p "$RELEASE_DIR"
rm -f "$DMG_PATH"
TEMP_DMG_DIR=$(mktemp -d)
cp -R "$APP_PATH" "$TEMP_DMG_DIR/"
hdiutil create -volname "$APP_NAME" \
    -srcfolder "$TEMP_DMG_DIR" \
    -ov -format UDZO \
    "$DMG_PATH" >/dev/null
rm -rf "$TEMP_DMG_DIR"

step "Sign DMG"
codesign --sign "$SIGN_IDENTITY" --timestamp "$DMG_PATH"

# 4. Notarize + staple
step "Submit for notarization (this can take 1-15 min)"
xcrun notarytool submit "$DMG_PATH" \
    --keychain-profile "$NOTARY_PROFILE" \
    --wait

step "Staple notarization ticket"
xcrun stapler staple "$DMG_PATH"
xcrun stapler validate "$DMG_PATH"

# 5. EdDSA sign for Sparkle
# In CI, pass the private key file directly via SPARKLE_PRIVATE_KEY_FILE
# to avoid keychain access prompts. Locally, the key is read from keychain.
step "EdDSA sign DMG for Sparkle"
if [[ -n "${SPARKLE_PRIVATE_KEY_FILE:-}" ]]; then
    SIGN_OUTPUT=$("$SIGN_UPDATE" -f "$SPARKLE_PRIVATE_KEY_FILE" "$DMG_PATH")
else
    SIGN_OUTPUT=$("$SIGN_UPDATE" "$DMG_PATH")
fi
echo "$SIGN_OUTPUT"
ED_SIG=$(echo "$SIGN_OUTPUT" | grep -oE 'sparkle:edSignature="[^"]+"' | sed 's/sparkle:edSignature="\(.*\)"/\1/')
ED_LEN=$(echo "$SIGN_OUTPUT" | grep -oE 'length="[0-9]+"' | sed 's/length="\([0-9]*\)"/\1/')

if [[ -z "$ED_SIG" || -z "$ED_LEN" ]]; then
    echo "❌ Failed to parse sign_update output"
    exit 1
fi

# 6. Update appcast.xml
step "Update appcast.xml"
PUB_DATE=$(LC_TIME=en_US.UTF-8 date -u +"%a, %d %b %Y %H:%M:%S +0000")

# Build inline release notes HTML from commit messages since previous tag.
# Inlining (vs sparkle:releaseNotesLink) avoids Sparkle rendering the entire
# GitHub repo page chrome inside the update dialog's WebView.
PREV_TAG=$(git tag --sort=-version:refname | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | grep -v "^v${VERSION}$" | head -n1 || true)
if [[ -n "$PREV_TAG" ]]; then
    COMMIT_RANGE="${PREV_TAG}..HEAD"
else
    COMMIT_RANGE="HEAD"
fi

NOTES_HTML=$(VERSION="$VERSION" PREV_TAG="$PREV_TAG" COMMIT_RANGE="$COMMIT_RANGE" python3 <<'PYEOF'
import html, os, subprocess

version = os.environ["VERSION"]
prev_tag = os.environ.get("PREV_TAG", "")
commit_range = os.environ["COMMIT_RANGE"]

result = subprocess.run(
    ["git", "log", commit_range, "--pretty=format:%s", "--reverse", "--no-merges"],
    capture_output=True, text=True, check=True,
)
lines = [l.strip() for l in result.stdout.splitlines() if l.strip()]
# Skip auto-generated release commits
lines = [l for l in lines if not l.startswith("release: v") and not l.startswith("chore: bump version")]

style = (
    "<style>"
    "body{font-family:-apple-system,BlinkMacSystemFont,sans-serif;font-size:13px;"
    "color:#1d1d1f;margin:8px 4px;line-height:1.5;}"
    "h2{font-size:14px;margin:0 0 8px 0;}"
    "ul{margin:0;padding-left:20px;}"
    "li{margin:2px 0;}"
    "code{background:#f5f5f7;padding:1px 4px;border-radius:3px;font-size:12px;}"
    "</style>"
)

if lines:
    items = "".join(f"<li>{html.escape(l)}</li>" for l in lines)
    body = f"<h2>What's Changed in v{html.escape(version)}</h2><ul>{items}</ul>"
else:
    body = f"<h2>Bartidy v{html.escape(version)}</h2><p>See release notes on GitHub.</p>"

print(style + body, end="")
PYEOF
)

# Escape for CDATA: split any "]]>" sequences (rare, but safe)
NOTES_HTML_SAFE=${NOTES_HTML//]]>/]]]]><![CDATA[>}

NEW_ITEM=$(cat <<EOF
        <item>
            <title>Version ${VERSION}</title>
            <pubDate>${PUB_DATE}</pubDate>
            <sparkle:version>${BUILD_NUMBER}</sparkle:version>
            <sparkle:shortVersionString>${VERSION}</sparkle:shortVersionString>
            <sparkle:minimumSystemVersion>13.0</sparkle:minimumSystemVersion>
            <description><![CDATA[${NOTES_HTML_SAFE}]]></description>
            <enclosure
                url="${DOWNLOAD_URL}"
                sparkle:edSignature="${ED_SIG}"
                length="${ED_LEN}"
                type="application/octet-stream" />
        </item>
EOF
)

if [[ ! -f "$APPCAST_PATH" ]]; then
    cat > "$APPCAST_PATH" <<EOF
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:sparkle="http://www.andymatuschak.org/xml-namespaces/sparkle">
    <channel>
        <title>Bartidy Updates</title>
        <link>https://raw.githubusercontent.com/raki-1203/bartidy/main/appcast.xml</link>
        <description>Most recent Bartidy releases</description>
        <language>en</language>
${NEW_ITEM}
    </channel>
</rss>
EOF
else
    # Insert new item at top of <channel>, after <language> tag
    APPCAST_PATH="$APPCAST_PATH" NEW_ITEM="$NEW_ITEM" python3 <<'PYEOF'
import os, re
path = os.environ["APPCAST_PATH"]
new_item = os.environ["NEW_ITEM"]
with open(path) as f:
    content = f.read()
# Insert after <language>...</language> (use lambda so HTML in new_item
# isn't reinterpreted as regex backreferences)
content = re.sub(
    r"(</language>\s*\n)",
    lambda m: m.group(1) + new_item + "\n",
    content, count=1,
)
with open(path, "w") as f:
    f.write(content)
PYEOF
fi

# Compute SHA256 for cask update
SHA256=$(shasum -a 256 "$DMG_PATH" | awk '{print $1}')

step "✅ Release artifact ready"
echo ""
echo "  DMG:        $DMG_PATH"
echo "  SHA256:     $SHA256"
echo "  Size:       $ED_LEN bytes"
echo "  EdSig:      $ED_SIG"
echo "  Appcast:    $APPCAST_PATH"
echo ""
echo "Next steps (manual):"
echo "  1. Review changes:      git diff appcast.xml Bartidy.xcodeproj/project.pbxproj"
echo "  2. Commit + tag:        git commit -am 'release: v${VERSION}' && git tag v${VERSION}"
echo "  3. Push:                git push origin main && git push origin v${VERSION}"
echo "  4. Create gh release:   gh release create v${VERSION} '${DMG_PATH}' --generate-notes"
echo "  5. Update cask SHA:     sed -i '' 's/sha256 \".*\"/sha256 \"${SHA256}\"/' Casks/bartidy.rb"
